-- Accounts, roles and the tokens the auth module hands out.
-- One profile per person: the same row is the buyer identity and the seller
-- storefront, so there is no separate shop entity.

CREATE TYPE user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'DEACTIVATED');

CREATE TYPE token_purpose AS ENUM ('REFRESH', 'PASSWORD_RESET');

-- Keeps updated_at honest no matter which statement touched the row.
CREATE FUNCTION set_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE user_account (
    id                    bigint       PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    email                 varchar(255) NOT NULL,
    password_hash         varchar(255) NOT NULL,
    username              varchar(50)  NOT NULL,
    display_name          varchar(100) NOT NULL,
    bio                   text,
    phone                 varchar(20),
    avatar_url            varchar(500),
    status                user_status  NOT NULL DEFAULT 'ACTIVE',
    failed_login_attempts smallint     NOT NULL DEFAULT 0,
    last_login_at         timestamptz,
    locked_until          timestamptz,
    created_at            timestamptz  NOT NULL DEFAULT now(),
    updated_at            timestamptz  NOT NULL DEFAULT now(),
    deleted_at            timestamptz,

    CONSTRAINT uq_user_account_email UNIQUE (email),
    CONSTRAINT uq_user_account_username UNIQUE (username),
    -- Stored folded, so the plain UNIQUE above is already case-insensitive.
    CONSTRAINT ck_user_account_email_lower CHECK (email = lower(email)),
    -- username is the public profile path /u/{username}.
    CONSTRAINT ck_user_account_username_format CHECK (username ~ '^[a-z0-9_]{3,50}$')
);

COMMENT ON COLUMN user_account.display_name IS 'Name buyers see next to a listing; there is no separate shop name.';
COMMENT ON COLUMN user_account.avatar_url IS 'Profile picture; stands in for a shop logo.';

CREATE INDEX ix_user_account_active ON user_account (id) WHERE deleted_at IS NULL;

CREATE TRIGGER trg_user_account_updated_at
    BEFORE UPDATE ON user_account
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE app_role (
    id          smallint    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code        varchar(32) NOT NULL,
    name        varchar(64) NOT NULL,
    description varchar(255),
    created_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_app_role_code UNIQUE (code)
);

-- A person holds several of these at once: nearly everyone is a BUYER and a
-- SELLER on the same account.
CREATE TABLE user_role (
    user_id    bigint      NOT NULL REFERENCES user_account (id) ON DELETE CASCADE,
    role_id    smallint    NOT NULL REFERENCES app_role (id) ON DELETE RESTRICT,
    granted_at timestamptz NOT NULL DEFAULT now(),
    granted_by bigint      REFERENCES user_account (id) ON DELETE SET NULL,

    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX ix_user_role_role_id ON user_role (role_id);

-- Refresh and password reset tokens. Only the SHA-256 of the value is kept, so
-- a database leak does not hand over live tokens.
CREATE TABLE auth_token (
    id         bigint        PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id    bigint        NOT NULL REFERENCES user_account (id) ON DELETE CASCADE,
    purpose    token_purpose NOT NULL,
    token_hash varchar(64)   NOT NULL,
    -- Every refresh token minted from one login shares a family; reuse of an
    -- already-rotated token revokes the whole family.
    family_id  uuid          NOT NULL,
    expires_at timestamptz   NOT NULL,
    used_at    timestamptz,
    revoked_at timestamptz,
    user_agent varchar(255),
    client_ip  varchar(45),
    created_at timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT uq_auth_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_auth_token_user_purpose ON auth_token (user_id, purpose);
CREATE INDEX ix_auth_token_family ON auth_token (family_id);
CREATE INDEX ix_auth_token_expires_at ON auth_token (expires_at);
