-- The slides at the top of the home page. Marketing changes these far more often
-- than the web client ships, so they are rows rather than hard-coded pictures.
CREATE TABLE home_banner (
    id              int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    eyebrow         varchar(60),
    title           varchar(120) NOT NULL,
    description     varchar(300),
    image_key       varchar(500) NOT NULL,
    image_alt       varchar(255),
    theme           varchar(20)  NOT NULL DEFAULT 'CAMPAIGN',
    primary_label   varchar(40),
    primary_href    varchar(500),
    secondary_label varchar(40),
    secondary_href  varchar(500),
    display_order   smallint     NOT NULL DEFAULT 0,
    is_active       boolean      NOT NULL DEFAULT true,
    starts_at       timestamptz,
    ends_at         timestamptz,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT ck_home_banner_theme CHECK (theme IN ('CAMPAIGN', 'RELEASE', 'COLLECTOR')),
    CONSTRAINT ck_home_banner_window CHECK (
        starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at)
);

COMMENT ON COLUMN home_banner.title IS
    'Line breaks are kept: the slide shows the title on as many lines as it is written.';
COMMENT ON COLUMN home_banner.image_key IS
    'MinIO object key, signed when the home page reads it.';
COMMENT ON COLUMN home_banner.starts_at IS
    'NULL shows the slide from now on; with ends_at, a campaign switches itself on and off.';

CREATE INDEX ix_home_banner_live ON home_banner (is_active, display_order);

CREATE TRIGGER trg_home_banner_updated_at
    BEFORE UPDATE ON home_banner
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
