

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE game (
    id            smallint     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code          varchar(32)  NOT NULL,
    name          varchar(100) NOT NULL,
    name_local    varchar(100),
    slug          varchar(100) NOT NULL,
    logo_url      varchar(500),
    display_order smallint     NOT NULL DEFAULT 0,
    is_active     boolean      NOT NULL DEFAULT true,
    created_by    bigint       REFERENCES user_account (id) ON DELETE SET NULL,
    created_at    timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_game_code UNIQUE (code),
    CONSTRAINT uq_game_slug UNIQUE (slug)
);

COMMENT ON TABLE game IS
    'Admins add a card game from the back office; no migration needed [RQ-3].';


-- The registry that makes multi-game work: it declares which fields a game has,
-- and catalog_product.attributes holds the values. A new game is rows, not DDL.
CREATE TABLE game_attribute (
    id            int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id       smallint     NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    attr_key      varchar(50)  NOT NULL,
    label         varchar(100) NOT NULL,
    data_type     varchar(32)  NOT NULL,
    options       jsonb,
    is_filterable boolean      NOT NULL DEFAULT true,
    is_required   boolean      NOT NULL DEFAULT false,
    display_order smallint     NOT NULL DEFAULT 0,

    CONSTRAINT ck_game_attribute_data_type CHECK (data_type IN
        ('STRING', 'NUMBER', 'BOOLEAN', 'ENUM', 'DATE')),
    -- Only ENUM attributes carry a choice list, and it has to be a JSON array.
    CONSTRAINT ck_game_attribute_options CHECK (
        (data_type = 'ENUM' AND jsonb_typeof(options) = 'array')
        OR (data_type <> 'ENUM' AND options IS NULL))
);

COMMENT ON COLUMN game_attribute.attr_key IS
    'The key used inside catalog_product.attributes, e.g. "hp", "mana_cost".';

CREATE UNIQUE INDEX ux_game_attribute_key ON game_attribute (game_id, attr_key);


CREATE TABLE catalog_category (
    id            int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id       smallint     REFERENCES game (id) ON DELETE CASCADE,
    parent_id     int          REFERENCES catalog_category (id) ON DELETE SET NULL,
    code          varchar(50)  NOT NULL,
    name          varchar(100) NOT NULL,
    slug          varchar(120) NOT NULL,
    display_order smallint     NOT NULL DEFAULT 0,
    is_active     boolean      NOT NULL DEFAULT true,

    CONSTRAINT ck_catalog_category_not_self CHECK (parent_id IS DISTINCT FROM id)
);

COMMENT ON COLUMN catalog_category.game_id IS
    'NULL means the category spans every game, e.g. Accessory.';

-- NULLS NOT DISTINCT so the cross-game categories (game_id IS NULL) still
-- cannot repeat a code.
CREATE UNIQUE INDEX ux_catalog_category_code
    ON catalog_category (game_id, code) NULLS NOT DISTINCT;
CREATE INDEX ix_catalog_category_parent ON catalog_category (parent_id);


CREATE TABLE card_set (
    id           int          PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id      smallint     NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    code         varchar(32)  NOT NULL,
    name         varchar(150) NOT NULL,
    name_local   varchar(150),
    release_date date,
    total_cards  int,
    logo_url     varchar(500)
);

CREATE UNIQUE INDEX ux_card_set_code ON card_set (game_id, code);
CREATE INDEX ix_card_set_release ON card_set (release_date);


-- The card as a concept: true whether or not anybody is selling one.
CREATE TABLE catalog_product (
    id           bigint       PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    game_id      smallint     NOT NULL REFERENCES game (id) ON DELETE RESTRICT,
    category_id  int          NOT NULL REFERENCES catalog_category (id) ON DELETE RESTRICT,
    card_set_id  int          REFERENCES card_set (id) ON DELETE SET NULL,
    product_type varchar(32)  NOT NULL DEFAULT 'SINGLE_CARD',
    name         varchar(255) NOT NULL,
    name_local   varchar(255),
    slug         varchar(300) NOT NULL,
    card_number  varchar(32),
    rarity_code  varchar(32),
    description  text,
    attributes   jsonb        NOT NULL DEFAULT '{}',
    is_active    boolean      NOT NULL DEFAULT true,
    created_by   bigint       REFERENCES user_account (id) ON DELETE SET NULL,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_catalog_product_slug UNIQUE (slug),
    CONSTRAINT ck_catalog_product_type CHECK (product_type IN
        ('SINGLE_CARD', 'BOOSTER_PACK', 'BOOSTER_BOX', 'ELITE_TRAINER_BOX',
         'STARTER_DECK', 'BUNDLE', 'ACCESSORY', 'OTHER')),
    CONSTRAINT ck_catalog_product_attributes CHECK (jsonb_typeof(attributes) = 'object')
);

COMMENT ON COLUMN catalog_product.attributes IS
    'Values for this game''s game_attribute keys. Validated in the service layer.';

CREATE INDEX ix_catalog_product_game_set ON catalog_product (game_id, card_set_id);
CREATE INDEX ix_catalog_product_browse ON catalog_product (game_id, product_type, is_active);

-- The two indexes DBML cannot express, and the reason the faceted search and
-- the name search stay fast once the catalogue is large.
CREATE INDEX ix_catalog_product_attributes
    ON catalog_product USING GIN (attributes jsonb_path_ops);
CREATE INDEX ix_catalog_product_name_trgm
    ON catalog_product USING GIN (name gin_trgm_ops);

CREATE TRIGGER trg_catalog_product_updated_at
    BEFORE UPDATE ON catalog_product
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- The unit that is actually traded. A Japanese foil and an English plain print
-- of one card are different money, so they are different rows; every median
-- price and market statistic is computed at this level [RQ-5].
CREATE TABLE catalog_variant (
    id                 bigint       PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    catalog_product_id bigint       NOT NULL REFERENCES catalog_product (id) ON DELETE CASCADE,
    sku                varchar(64)  NOT NULL,
    language_code      varchar(10)  NOT NULL DEFAULT 'EN',
    finish             varchar(32)  NOT NULL DEFAULT 'NORMAL',
    edition            varchar(32)  NOT NULL DEFAULT 'NOT_APPLICABLE',
    printing_note      varchar(100),
    barcode            varchar(64),
    image_url          varchar(500),
    is_active          boolean      NOT NULL DEFAULT true,
    created_at         timestamptz  NOT NULL DEFAULT now(),

    CONSTRAINT uq_catalog_variant_sku UNIQUE (sku),
    CONSTRAINT ck_catalog_variant_finish CHECK (finish IN
        ('NORMAL', 'HOLO', 'REVERSE_HOLO', 'FOIL', 'ETCHED', 'TEXTURED', 'NOT_APPLICABLE')),
    CONSTRAINT ck_catalog_variant_edition CHECK (edition IN
        ('FIRST_EDITION', 'UNLIMITED', 'PROMO', 'NOT_APPLICABLE'))
);

-- printing_note is nullable and part of the identity, so NULLS NOT DISTINCT is
-- what actually stops a duplicate plain print.
CREATE UNIQUE INDEX ux_catalog_variant_identity
    ON catalog_variant (catalog_product_id, language_code, finish, edition, printing_note)
    NULLS NOT DISTINCT;
CREATE INDEX ix_catalog_variant_product ON catalog_variant (catalog_product_id);


CREATE TABLE catalog_image (
    id                 bigint       PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    catalog_product_id bigint       NOT NULL REFERENCES catalog_product (id) ON DELETE CASCADE,
    catalog_variant_id bigint       REFERENCES catalog_variant (id) ON DELETE CASCADE,
    image_key          varchar(500) NOT NULL,
    alt_text           varchar(255),
    sort_order         smallint     NOT NULL DEFAULT 0,
    is_primary         boolean      NOT NULL DEFAULT false
);

COMMENT ON COLUMN catalog_image.catalog_variant_id IS
    'NULL means the image is shared by every variant of the product.';

CREATE INDEX ix_catalog_image_product ON catalog_image (catalog_product_id, sort_order);

CREATE UNIQUE INDEX ux_catalog_image_primary
    ON catalog_image (catalog_product_id)
    WHERE is_primary;
